matrix:
  include:
    - language: python
      python: 3.7
      before_install:
        - cd backend
      install:
        - pip install -r requirements.txt
      script:
        - pytest ./tests/test.py

    - language: node_js
      node_js: 15
      before_install:
        - cd frontend
      cache:
        directories:
          - node_modules
      # command to install dependencies
      install:
        - npm install
      # command to run tests
      script:
        - npm test