services:
  backend:
    image: colemclark/my-app:backend
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "3000:5000"
  frontend:
    image: colemclark/my-app:frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "8080:8080"
  database:
    image: postgres:12
    container_name: database
    ports:
      - "5400:5432"
    expose:
      - 5400
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_DB=my-app
      - POSTGRES_HOST_AUTH_METHOD=trust