apiVersion: apps/v1
kind: Deployment
metadata:
    name: postgres-deploy
    labels:
        app: postgresdb
spec:
    replicas: 1
    selector:
            matchLabels:
                app: postgresdb
    template:
        metadata:
            labels:
                app: postgresdb
        spec:
            containers:
            - name: postgresdb
              image: postgres
              ports:
              - containerPort: 5432
              env:
              - name: POSTGRES_PASSWORD
                valueFrom: 
                  secretKeyRef:
                    name: postgres-secret
                    key: db-password
              - name: POSTGRES_USER
                valueFrom: 
                  secretKeyRef:
                    name: postgres-secret
                    key: db-username
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgresdb
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432