"""Initial migration.

Revision ID: b76b02ba1c50
Revises: 
Create Date: 2021-03-28 21:11:25.252957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b76b02ba1c50'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=100), nullable=True))
    op.alter_column('user', 'firstName',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'lastName',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'lastName',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'firstName',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
